/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: linux-x86_64"
#define DATE "built on: Wed Jul 31 20:34:29 2024 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','g','c','c',' ','-','f',
    'P','I','C',' ','-','p','t','h','r','e','a','d',' ','-','m','6',
    '4',' ','-','W','a',',','-','-','n','o','e','x','e','c','s','t',
    'a','c','k',' ','-','W','a','l','l',' ','-','O','3',' ','-','D',
    'O','P','E','N','S','S','L','_','U','S','E','_','N','O','D','E',
    'L','E','T','E',' ','-','D','L','_','E','N','D','I','A','N',' ',
    '-','D','O','P','E','N','S','S','L','_','P','I','C',' ','-','D',
    'O','P','E','N','S','S','L','_','B','U','I','L','D','I','N','G',
    '_','O','P','E','N','S','S','L',' ','-','D','N','D','E','B','U',
    'G',' ','-','D','O','P','E','N','S','S','L','_','N','O','_','H',
    'E','A','R','T','B','E','A','T','S',' ','-','D','O','Q','S','_',
    'D','E','F','A','U','L','T','_','G','R','O','U','P','S','=','"',
    'p','3','8','4','_','k','y','b','e','r','7','6','8',':','p','3',
    '8','4','_','k','y','b','e','r','1','0','2','4',':','p','5','2',
    '1','_','k','y','b','e','r','1','0','2','4',':','k','y','b','e',
    'r','7','6','8',':','k','y','b','e','r','1','0','2','4',':','p',
    '3','8','4','_','f','a','l','c','o','n','5','1','2',':','p','5',
    '2','1','_','f','a','l','c','o','n','1','0','2','4',':','f','a',
    'l','c','o','n','5','1','2',':','f','a','l','c','o','n','1','0',
    '2','4',':','p','3','8','4','_','d','i','l','i','t','h','i','u',
    'm','3',':','p','5','2','1','_','d','i','l','i','t','h','i','u',
    'm','5',':','d','i','l','i','t','h','i','u','m','3',':','d','i',
    'l','i','t','h','i','u','m','5','"','\0'
};
